### ISSUE TITLE
登录提示“Authentication failed..."

### ISSUE THREAD

**Issue by S4kur4** [vicalloy/outline-docker-compose#2]
Hi，关于部署后登录提示“Authentication failed..."，下面是wk-outline的logs：
```
wk-outline_1        | {"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","message":"Error during authentication"}
wk-outline_1        | {"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","message":"Error during authentication"}
wk-outline_1        | {"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","message":"Error during authentication"}
wk-outline_1        | {"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:390:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:447:9)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","message":"Error during authentication"}
```
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/17521941/154494604-a6d06361-d5ba-4047-bc7e-f13ee9f942af.png">

我是部署在公网上，config.sh中URL填的公网地址。这里会不会跟TLS相关？

**Comment by vicalloy** [comment]
你把你的 `config.sh` 贴出来看看。错误信息应当是outline在容器里访问oidc server接口的时候失败了。

**Comment by vicalloy** [comment]
@wujie1993 恩，这是个bug，每次start都会将配置文件生成一次，env文件里OIDC_CLIENT_SECRET变了，数据库里没有变。我想想怎么修改一下脚本。

**Comment by vicalloy** [comment]
@wujie1993 问题修正了。现在生成的SECRET会保存到config.sh，后续再执行 `make start` 的时候 OIDC_CLIENT_SECRET 不会变了。需要在config.sh里增加下面的设置
```
# Secret keys, update by script
# you shouldn't edit it
MINIO_ACCESS_KEY=
MINIO_SECRET_KEY=
OIDC_CLIENT_SECRET=
OUTLINE_SECRET_KEY=
OUTLINE_UTILS_SECRET=
DJANGO_SECRET_KEY=
```

**Comment by S4kur4** [comment]
> 你把你的 `config.sh` 贴出来看看。 另外你可以更新一下部署脚本到最新版本，可能可以解决该问题。 新脚本里对OIDC服务接口访问失败的问题做了一些优化。 另外 `FORCE_HTTPS` 不要修改，设置成 `true` 可能会有问题。

使用了新的脚本部署认证成功了，Thanks!
另外想问一下，我在Outline点击退出登录，然后重新点击`Continue with OpenID`发现又登进去了，这里是不是应该在点击后使用账号密码重新登录呢？

https://user-images.githubusercontent.com/17521941/154625130-e2c21eb1-ce2d-4399-a6b4-49cf43ac8eb2.mp4

**Comment by vicalloy** [comment]
@S4kur4 使用OIDC服务登录和你通过Github登录其他网站类似，要彻底退出还需要将ODIC服务器退出。使用 http://127.0.0.1:8888/uc/ 右上角的logout退出。
