### ISSUE TITLE
outline容器启动失败

### ISSUE THREAD

**Issue by baka-gourd** [vicalloy/outline-docker-compose#22]
ERROR: The server does not support SSL connections
```
yarn run v1.22.18
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.4.1, ORM: 6.20.1]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 0.85s.
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
ERROR: The server does not support SSL connections
error Command failed with exit code 1.
node:child_process:828
    err = new Error(msg);
          ^

Error: Command failed: yarn sequelize db:migrate:status
ERROR: The server does not support SSL connections
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at checkPendingMigrations (/opt/outline/build/server/utils/startup.js:25:53)
    at master (/opt/outline/build/server/index.js:68:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async throng (/opt/outline/node_modules/throng/lib/throng.js:31:3) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(303) [Uint8Array] [
       36,  32,  47, 111, 112, 116,  47, 111, 117, 116, 108, 105,
      110, 101,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
      108, 101, 115,  47,  46,  98, 105, 110,  47, 115, 101, 113,
      117, 101, 108, 105, 122, 101,  32, 100,  98,  58, 109, 105,
      103, 114,  97, 116, 101,  58, 115, 116,  97, 116, 117, 115,
       10,  10,  27,  91,  52, 109,  83, 101, 113, 117, 101, 108,
      105, 122, 101,  32,  67,  76,  73,  32,  91,  78, 111, 100,
      101,  58,  32,  49,  54,  46,  49,  52,  46,  50,  44,  32,
       67,  76,  73,  58,
      ... 203 more items
    ],
    Buffer(100) [Uint8Array] [
       27,  91,  51,  49, 109,  69,  82,  82,  79,  82,  58,  27,
       91,  51,  57, 109,  32,  84, 104, 101,  32, 115, 101, 114,
      118, 101, 114,  32, 100, 111, 101, 115,  32, 110, 111, 116,
       32, 115, 117, 112, 112, 111, 114, 116,  32,  83,  83,  76,
       32,  99, 111, 110, 110, 101,  99, 116, 105, 111, 110, 115,
       10, 101, 114, 114, 111, 114,  32,  67, 111, 109, 109,  97,
      110, 100,  32, 102,  97, 105, 108, 101, 100,  32, 119, 105,
      116, 104,  32, 101, 120, 105, 116,  32,  99, 111, 100, 101,
       32,  49,  46,  10
    ]
  ],
  pid: 71,
  stdout: Buffer(303) [Uint8Array] [
     36,  32,  47, 111, 112, 116,  47, 111, 117, 116, 108, 105,
    110, 101,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
    108, 101, 115,  47,  46,  98, 105, 110,  47, 115, 101, 113,
    117, 101, 108, 105, 122, 101,  32, 100,  98,  58, 109, 105,
    103, 114,  97, 116, 101,  58, 115, 116,  97, 116, 117, 115,
     10,  10,  27,  91,  52, 109,  83, 101, 113, 117, 101, 108,
    105, 122, 101,  32,  67,  76,  73,  32,  91,  78, 111, 100,
    101,  58,  32,  49,  54,  46,  49,  52,  46,  50,  44,  32,
     67,  76,  73,  58,
    ... 203 more items
  ],
  stderr: Buffer(100) [Uint8Array] [
     27,  91,  51,  49, 109,  69,  82,  82,  79,  82,  58,  27,
     91,  51,  57, 109,  32,  84, 104, 101,  32, 115, 101, 114,
    118, 101, 114,  32, 100, 111, 101, 115,  32, 110, 111, 116,
     32, 115, 117, 112, 112, 111, 114, 116,  32,  83,  83,  76,
     32,  99, 111, 110, 110, 101,  99, 116, 105, 111, 110, 115,
     10, 101, 114, 114, 111, 114,  32,  67, 111, 109, 109,  97,
    110, 100,  32, 102,  97, 105, 108, 101, 100,  32, 119, 105,
    116, 104,  32, 101, 120, 105, 116,  32,  99, 111, 100, 101,
     32,  49,  46,  10
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by baka-gourd** [comment]
已经把能关的ssl全部都关掉了

**Comment by baka-gourd** [comment]
使用[0.63.0](https://hub.docker.com/layers/outline/outlinewiki/outline/0.63.0/images/sha256-4b7ccf4108b86683a33ac82213959c0a853c8ad57220fa92825fd7969b146c3d?context=explore)解决问题

**Comment by vicalloy** [comment]
应当是 outline 的问题 https://github.com/outline/outline/issues/3810
