### ISSUE TITLE
Export uploads do not work

### ISSUE THREAD

**Issue by 50bbx** [vicalloy/outline-docker-compose#46]
I am trying to upload an export from the cloud version of Outline.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/3308680/211519005-00e71e4d-f007-4a49-97c4-a365a5de1fab.png">

The issue is that it doesn't work and I can get a hint of the issue when looking at `wk-outline` logs:

```
{
   "error":"Inaccessible host: `127.0.0.1' at port `8888'. This service may not be available in the `xx-xxxx-x' region.",
   "stack":"UnknownEndpoint: Inaccessible host: `127.0.0.1' at port `8888'. This service may not be available in the `xx-xxxx-x' region.\n    at Request.ENOTFOUND_ERROR (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:557:46)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:686:14)\n    at error (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:389:22)\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/http/node.js:99:9)\n    at ClientRequest.emit (node:events:526:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at Socket.socketErrorListener (node:_http_client:442:9)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
   "level":"error",
   "message":"Error getting file from S3 by key"
}{
   "error":"Failed to fetch data for import from storage.",
   "stack":"InternalServerError: Failed to fetch data for import from storage.\n    at InternalError (/opt/outline/build/server/errors.js:35:34)\n    at ImportMarkdownZipTask.perform (/opt/outline/build/server/queues/tasks/ImportTask.js:55:41)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)",
   "level":"error",
   "message":"Error processing task in ImportMarkdownZipTask"
}
```

I think that importing an Outline exports works like this:
- The user uploads the zip from the frontend
- The frontend uploads the zip to to minio
- The frontend gives the attachment id to the Outline server
- The Outline server tries to download the zip from minio
As you can see, the outline server tries to connect to 127.0.0.1:8888 but of course it can't because there is no process running on port 8888 inside the container.

It looks like a config error. Is there a variable to define the minio's server side URL? It should be something like `http://wk-minio:9000`

**Comment by g4ngli0s** [comment]
I have the same error but exporting the data. Have you found the solution?
